version: '3.9'

services:
  iotzoo:
    image: ${DOCKER_REGISTRY-}iotzoo
    restart: always
    build:
      context: .
      dockerfile: UI/Blazor/Dockerfile


  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ../DataAccess/DataModel/Postgres.plsql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=<PasswordForPostgres>
      - POSTGRES_USER=postgres
      - POSTGRES_DB=IoTZoo
